### ISSUE TITLE
How can I fix this on Windows 10

### ISSUE THREAD

**Issue by vlkalashnikov** [kolesa-team/go-webp#14]
![image](https://user-images.githubusercontent.com/38080855/184975322-181549ca-581e-4003-bf34-ac0b7e079169.png)

**Comment by alenapetraki** [comment]
@vlkalashnikov have you fixed it somehow? Wanna share?:)

**Comment by vlkalashnikov** [comment]
@alenapetraki 

Download libwebp-dev library and put it to project directory
