### ISSUE TITLE
Failed to compile from Windows too.

### ISSUE THREAD

**Issue by yuxiaobo96** [kolesa-team/go-webp#28]
I get an error when compiling the program.
![image](https://github.com/kolesa-team/go-webp/assets/41496192/61f793f7-2efd-4473-b4bc-01999148d533)

Compiler Environment：
Windows11
goland
Go version: 1.19.8

**Comment by linksquidmx** [comment]
Try reading #19 , it's the same problem with the webplib files.

**Comment by dadencukillia** [comment]
You need to install [MinGW](https://code.visualstudio.com/docs/cpp/config-mingw), libwebp and specify `CGO_ENABLED=1` when compiling/running the program.
