### ISSUE TITLE
cannot fetch features: VP8_STATUS_BITSTREAM_ERROR

### ISSUE THREAD

**Issue by frops** [kolesa-team/go-webp#9]
I'm trying to convert png to webp and getting error "cannot fetch features: VP8_STATUS_BITSTREAM_ERROR".

```go
func (c *ConvertService) ConvertToWebp(file io.Reader, d entities.Dimensions) (image.Image, error) {
	img, err := webp.Decode(file, &decoder.Options{})

	if err != nil {
		return nil, err
	}

	return transform.Resize(img, d.Width, d.Height, transform.Linear), nil
}
```

**OS**: macOS Catalina, 10.15.7
**Lib**: webp 1.2.1
**Go**: 1.17

**Comment by lEx0** [comment]
are you opening png file with webp decoder?

**Comment by frops** [comment]
> are you opening png file with webp decoder?

No, i'm using io.Reader

**Comment by lEx0** [comment]
If I understand correctly, you try to open png file by webp decoder, right?
if i'm right, firstly you have to open png file with png decoder and try encode result image.Image with webp encoder to create webp picture
